-- ============================================================
-- ClashStatsPro — Historical Stats Import
-- Source: clash.co.nz/stats (snapshot 2026-01-26)
-- Raw counts reconstructed from per-event averages × played.
-- Safe to re-run: ON CONFLICT updates existing rows.
-- ============================================================

-- ── Step 1: Insert all 75 players ────────────────────────────
-- discord_id is NULL (will be linked when players sign in via Discord)
-- status = 'approved' so they appear in rankings immediately
-- region = 'Oceania' (NZ-based league)

INSERT INTO players (username, display_name, club, region, ranking_points, status)
VALUES
  ('isaac',            'ISAAC',              'BBC',           'Oceania',  32, 'approved'),
  ('damascus',         'Damascus',           'Landscape',     'Oceania',  13, 'approved'),
  ('allan',            'ALLAN',              'Landscape',     'Oceania',  11, 'approved'),
  ('air',              'AIR',                'Free Agent',    'Oceania',  10, 'approved'),
  ('cyrus',            'CYRUS',              'Slay Bladers',  'Oceania',   8, 'approved'),
  ('byron',            'BYRON',              'Free Agent',    'Oceania',   8, 'approved'),
  ('zach',             'ZACH',               'Free Agent',    'Oceania',   7, 'approved'),
  ('koi',              'KOI',                '4-2',           'Oceania',   6, 'approved'),
  ('drawzy',           'DRAWZY',             'BBC',           'Oceania',   6, 'approved'),
  ('feign',            'FEIGN',              'BBC',           'Oceania',   5, 'approved'),
  ('bntrs',            'BNTRS',              'Team Astral',   'Oceania',   5, 'approved'),
  ('cortez',           'CORTEZ',             'Team Astral',   'Oceania',   5, 'approved'),
  ('gatito',           'GATITO',             'Team Astral',   'Oceania',   5, 'approved'),
  ('black',            'BLACK',              'BXW',           'Oceania',   4, 'approved'),
  ('denise',           'DENISE',             'Slay Bladers',  'Oceania',   4, 'approved'),
  ('antonio',          'ANTONIO',            'Free Agent',    'Oceania',   4, 'approved'),
  ('daddy_bear',       'DADDY BEAR',         'Free Agent',    'Oceania',   4, 'approved'),
  ('mastery_jho',      'MASTERY JHO',        'Free Agent',    'Oceania',   4, 'approved'),
  ('seeker',           'SEEKER',             'Landscape',     'Oceania',   3, 'approved'),
  ('master_bleyder',   'MASTER BLEYDER',     'Free Agent',    'Oceania',   3, 'approved'),
  ('eepybunnz',        'EeepyBunnz',         'Free Agent',    'Oceania',   3, 'approved'),
  ('king_leo',         'KING LEO',           'Slay Bladers',  'Oceania',   3, 'approved'),
  ('barry',            'BARRY',              'Free Agent',    'Oceania',   3, 'approved'),
  ('mary_mu',          'Mary Mu',            'Free Agent',    'Oceania',   3, 'approved'),
  ('wai',              'Wai',                'Free Agent',    'Oceania',   3, 'approved'),
  ('nathan',           'NATHAN',             'BBC',           'Oceania',   2, 'approved'),
  ('no_dran_buster',   'NO DRAN BUSTER',     'Free Agent',    'Oceania',   2, 'approved'),
  ('liam_the_lloyd',   'LIAM THE LLOYD',     'Free Agent',    'Oceania',   2, 'approved'),
  ('corbin_h',         'CORBIN H',           'Free Agent',    'Oceania',   2, 'approved'),
  ('brother_bear',     'BROTHER BEAR',       'Free Agent',    'Oceania',   2, 'approved'),
  ('raych',            'RAYCH',              'Slay Bladers',  'Oceania',   2, 'approved'),
  ('blader_a',         'BLADER A',           'Free Agent',    'Oceania',   2, 'approved'),
  ('fluffy_bunny',     'FLUFFY BUNNY',       'BBC',           'Oceania',   2, 'approved'),
  ('ben_h',            'BEN H',              'Free Agent',    'Oceania',   2, 'approved'),
  ('its_andii',        'ITS ANDII',          'Free Agent',    'Oceania',   2, 'approved'),
  ('junior_bear',      'JUNIOR BEAR',        'Free Agent',    'Oceania',   2, 'approved'),
  ('glover',           'GLOVER',             'Free Agent',    'Oceania',   2, 'approved'),
  ('blader_x_emmet',   'Blader X - Emmet',   'Landscape',     'Oceania',   2, 'approved'),
  ('big_chilli',       'BIG CHILLI',         'Free Agent',    'Oceania',   1, 'approved'),
  ('bodhi',            'BODHI',              'Free Agent',    'Oceania',   1, 'approved'),
  ('bey_mechanic',     'BEY MECHANIC',       '4-2',           'Oceania',   1, 'approved'),
  ('akino',            'AKINO',              'Free Agent',    'Oceania',   1, 'approved'),
  ('ricky_lo',         'RICKY LO',           'Free Agent',    'Oceania',   1, 'approved'),
  ('aryan',            'ARYAN',              'Free Agent',    'Oceania',   1, 'approved'),
  ('blader_ros',       'BLADER ROS',         'Free Agent',    'Oceania',   1, 'approved'),
  ('odin',             'ODIN',               'Free Agent',    'Oceania',   1, 'approved'),
  ('gdara',            'GDARA',              'Beytalis',      'Oceania',   1, 'approved'),
  ('nolan',            'NOLAN',              'Free Agent',    'Oceania',   1, 'approved'),
  ('pigu',             'PIGU',               'Free Agent',    'Oceania',   1, 'approved'),
  ('wes',              'WES',                'Free Agent',    'Oceania',   1, 'approved'),
  ('aryoos',           'ARYOOS',             'Free Agent',    'Oceania',   1, 'approved'),
  ('alexbot',          'ALEXBOT',            'Team Astral',   'Oceania',   1, 'approved'),
  ('cat_5',            'CAT 5',              'Free Agent',    'Oceania',   1, 'approved'),
  ('jackson',          'JACKSON',            'Free Agent',    'Oceania',   1, 'approved'),
  ('maverick',         'MAVERICK',           'Free Agent',    'Oceania',   1, 'approved'),
  ('daney',            'DANEY',              'Free Agent',    'Oceania',   1, 'approved'),
  ('elemani',          'ELEMANI',            'Free Agent',    'Oceania',   1, 'approved'),
  ('flame_boi',        'FLAME BOI',          'Free Agent',    'Oceania',   1, 'approved'),
  ('adrian_lo',        'ADRIAN LO',          'Free Agent',    'Oceania',   1, 'approved'),
  ('vayne',            'VAYNE',              'Free Agent',    'Oceania',   1, 'approved'),
  ('beau',             'BEAU',               'Free Agent',    'Oceania',   1, 'approved'),
  ('donell',           'DONELL',             'Free Agent',    'Oceania',   1, 'approved'),
  ('banri',            'BANRI',              'Free Agent',    'Oceania',   1, 'approved'),
  ('theo_r',           'THEO R',             'Free Agent',    'Oceania',   1, 'approved'),
  ('moss',             'MOSS',               'Free Agent',    'Oceania',   1, 'approved'),
  ('lion',             'LION',               'Free Agent',    'Oceania',   1, 'approved'),
  ('vanzilla',         'Vanzilla',           'Free Agent',    'Oceania',   1, 'approved'),
  ('vish',             'Vish',               'Free Agent',    'Oceania',   1, 'approved'),
  ('meta_maahi',       'Meta Maahi',         'Free Agent',    'Oceania',   1, 'approved'),
  ('tomp',             'TomP',               '4-2',           'Oceania',   1, 'approved'),
  ('king_blader',      'King Blader',        'Free Agent',    'Oceania',   1, 'approved'),
  ('master_jai',       'Master Jai',         'Free Agent',    'Oceania',   1, 'approved'),
  ('bey_mysterio_snr', 'Bey Mysterio Snr',   'Independent',   'Oceania',   1, 'approved'),
  ('blader_k',         'Blader K',           'Independent',   'Oceania',   1, 'approved'),
  ('blader_b',         'Blader B',           'Independent',   'Oceania',   1, 'approved')
ON CONFLICT (username) DO UPDATE SET
  display_name   = EXCLUDED.display_name,
  club           = EXCLUDED.club,
  region         = EXCLUDED.region,
  ranking_points = EXCLUDED.ranking_points,
  status         = 'approved';

-- ── Step 2: Insert historical player_stats ────────────────────
-- Raw counts = ROUND(ratio × tournaments_entered)
-- matches_played / matches_won start at 0 (not tracked in SportPress)
-- win_rate starts at 0 (will accumulate from new matches going forward)

INSERT INTO player_stats (player_id, tournaments_entered, spn_count, bur_count, ovr_count, ext_count, pen_count, swiss_king_total, matches_played, matches_won, win_rate, updated_at)
SELECT p.id, v.te, v.spn, v.bur, v.ovr, v.ext, v.pen, v.sk, 0, 0, 0, NOW()
FROM players p
JOIN (VALUES
  --            username              te   spn  bur  ovr  ext  pen  sk
  ('isaac',                            3,   11,   4,   6,   7,   0,  1),
  ('damascus',                         2,    2,   0,   0,   0,   0,  0),
  ('allan',                            2,   13,   4,   7,   6,   0,  0),
  ('air',                              3,   15,   1,   6,   3,   0,  0),
  ('cyrus',                            3,    8,   1,   5,   3,   1,  0),
  ('byron',                            3,   14,   0,   3,   1,   0,  0),
  ('zach',                             2,   27,   0,   5,   2,   0,  0),
  ('koi',                              3,   10,   2,   3,   3,   1,  0),
  ('drawzy',                           3,    8,   2,   2,   3,   0,  0),
  ('feign',                            3,   10,   0,   8,   0,   1,  0),
  ('bntrs',                            3,    9,   3,   4,   3,   1,  1),
  ('cortez',                           3,    7,   1,   5,   2,   2,  1),
  ('gatito',                           3,    3,   0,   1,   3,   1,  0),
  ('black',                            1,   12,   3,   3,   8,   0,  0),
  ('denise',                           2,   17,   2,   5,   3,   2,  0),
  ('antonio',                          2,    6,   2,   4,   4,   0,  0),
  ('daddy_bear',                       2,    7,   0,   6,   1,   1,  0),
  ('mastery_jho',                      2,    9,   1,   2,   1,   2,  0),
  ('seeker',                           1,   25,   0,   3,   2,   0,  0),
  ('master_bleyder',                   1,   16,   2,   0,   3,   2,  0),
  ('eepybunnz',                        3,    5,   1,   3,   4,   3,  0),
  ('king_leo',                         3,    3,   2,   4,   2,   2,  0),
  ('barry',                            3,   10,   1,   2,   2,   0,  0),
  ('mary_mu',                          1,    0,   0,   0,   0,   0,  0),
  ('wai',                              1,    0,   0,   0,   0,   0,  0),
  ('nathan',                           2,   14,   1,   4,   1,   1,  0),
  ('no_dran_buster',                   2,   12,   0,   1,   4,   4,  0),
  ('liam_the_lloyd',                   2,    8,   4,   2,   2,   0,  0),
  ('corbin_h',                         2,    5,   1,   0,   3,   0,  0),
  ('brother_bear',                     2,    8,   0,   1,   4,   2,  0),
  ('raych',                            2,    7,   0,   4,   2,   0,  0),
  ('blader_a',                         2,    9,   2,   3,   1,   1,  0),
  ('fluffy_bunny',                     2,   11,   0,   1,   3,   0,  0),
  ('ben_h',                            2,    9,   0,   2,   1,   3,  0),
  ('its_andii',                        2,    4,   0,   5,   1,   0,  0),
  ('junior_bear',                      2,    5,   0,   0,   3,   2,  0),
  ('glover',                           2,    6,   0,   3,   1,   0,  0),
  ('blader_x_emmet',                   2,    0,   0,   0,   0,   0,  0),
  ('big_chilli',                       1,    9,   0,   2,   4,   0,  0),
  ('bodhi',                            1,    4,   1,   3,   4,   1,  0),
  ('bey_mechanic',                     1,    4,   2,   5,   3,   0,  0),
  ('akino',                            1,    7,   3,   2,   2,   0,  0),
  ('ricky_lo',                         1,    9,   2,   3,   1,   1,  0),
  ('aryan',                            1,    8,   0,   7,   1,   0,  0),
  ('blader_ros',                       1,    6,   1,   3,   2,   3,  0),
  ('odin',                             1,   10,   1,   2,   2,   0,  0),
  ('gdara',                            1,    4,   0,   2,   3,   5,  0),
  ('nolan',                            1,    6,   0,   3,   2,   0,  0),
  ('pigu',                             1,    4,   2,   2,   5,   0,  0),
  ('wes',                              1,    4,   2,   4,   1,   2,  0),
  ('aryoos',                           1,   12,   0,   2,   1,   0,  0),
  ('alexbot',                          1,    5,   2,   4,   1,   0,  0),
  ('cat_5',                            1,    2,   2,   2,   3,   0,  0),
  ('jackson',                          1,    3,   0,   3,   3,   1,  0),
  ('maverick',                         1,    3,   0,   1,   3,   0,  0),
  ('daney',                            1,    9,   2,   2,   0,   1,  0),
  ('elemani',                          1,    2,   2,   2,   1,   1,  0),
  ('flame_boi',                        1,    9,   1,   3,   0,   0,  0),
  ('adrian_lo',                        1,   13,   0,   0,   1,   1,  0),
  ('vayne',                            1,    3,   1,   4,   1,   0,  0),
  ('beau',                             1,    4,   0,   4,   1,   0,  0),
  ('donell',                           1,    4,   1,   0,   0,   2,  0),
  ('banri',                            1,    3,   1,   0,   2,   1,  0),
  ('theo_r',                           1,    2,   0,   2,   0,   1,  0),
  ('moss',                             1,    1,   0,   2,   0,   0,  0),
  ('lion',                             1,    2,   1,   0,   0,   0,  0),
  ('vanzilla',                         1,    0,   0,   0,   0,   0,  0),
  ('vish',                             1,    0,   0,   0,   0,   0,  0),
  ('meta_maahi',                       1,    0,   0,   0,   0,   0,  0),
  ('tomp',                             1,    0,   0,   0,   0,   0,  0),
  ('king_blader',                      1,    0,   0,   0,   0,   0,  0),
  ('master_jai',                       1,    0,   0,   0,   0,   0,  0),
  ('bey_mysterio_snr',                 1,    1,   0,   0,   0,   1,  0),
  ('blader_k',                         1,    1,   0,   0,   0,   0,  0),
  ('blader_b',                         1,    1,   0,   0,   1,   0,  0)
) AS v(username, te, spn, bur, ovr, ext, pen, sk) ON p.username = v.username
ON CONFLICT (player_id) DO UPDATE SET
  tournaments_entered = EXCLUDED.tournaments_entered,
  spn_count           = EXCLUDED.spn_count,
  bur_count           = EXCLUDED.bur_count,
  ovr_count           = EXCLUDED.ovr_count,
  ext_count           = EXCLUDED.ext_count,
  pen_count           = EXCLUDED.pen_count,
  swiss_king_total    = EXCLUDED.swiss_king_total,
  updated_at          = NOW();
